# Generated by Django 3.1.7 on 2022-03-23 18:16

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeOffense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guilty', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'administrative_offense',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55)),
                ('description', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'attendance_status',
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'blood_type',
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'citizenship',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
            ],
            options={
                'db_table': 'civil_status',
            },
        ),
        migrations.CreateModel(
            name='Consanguity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_third_degree', models.BooleanField(default=False)),
                ('is_fourth_degree', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'consanguity',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='', max_length=55, unique=True)),
            ],
            options={
                'db_table': 'content_type',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(default=0)),
                ('reciever', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='Conviction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_convicted', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'conviction',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='CriminalCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_charged', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'criminal_charge',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
                ('tel_no', models.CharField(blank=True, default='None', max_length=15)),
                ('email', models.CharField(blank=True, default='None', max_length=100)),
                ('image', models.ImageField(blank=True, default='images/department/default.jpg', max_length=255, null=True, upload_to='images/department/')),
                ('department_head_id', models.IntegerField(default=0)),
                ('created_at', models.CharField(default='2022-03-23', max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, default='', max_length=15)),
                ('school_name', models.CharField(blank=True, default='', max_length=15)),
                ('course', models.CharField(blank=True, default='', max_length=15)),
                ('year_from', models.CharField(blank=True, default='', max_length=5)),
                ('year_to', models.CharField(blank=True, default='', max_length=5)),
                ('units_earned', models.IntegerField(default=0)),
                ('date_graduated', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'educational_background',
            },
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_candidate', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'election_candidate',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(default='', max_length=15, unique=True)),
                ('sur_name', models.CharField(default='', max_length=55)),
                ('first_name', models.CharField(default='', max_length=55)),
                ('middle_name', models.CharField(blank=True, default='', max_length=55)),
                ('birthdate', models.CharField(blank=True, default='', max_length=11)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(blank=True, default=0)),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('mobile_no', models.CharField(blank=True, default='', max_length=15)),
                ('tel_no', models.CharField(blank=True, default='', max_length=15)),
                ('date_hired', models.CharField(blank=True, default='', max_length=50)),
                ('start_date', models.CharField(blank=True, default='', max_length=30)),
                ('end_date', models.CharField(blank=True, default='', max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='images/employee/default.png', max_length=255, null=True, upload_to='images/employee/')),
                ('birthplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bloodtype')),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.citizenship')),
                ('civil_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.civilstatus')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'employee_status',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
                ('is_with_end_date', models.BooleanField(default=False)),
                ('is_auto_generate_no', models.BooleanField(default=False)),
                ('period', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'employee_type',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name_code', models.CharField(default='', max_length=55)),
                ('property_number', models.CharField(default='', max_length=55, unique=True)),
                ('description', models.TextField(default='', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('location', models.TextField(default='', max_length=255)),
                ('condition', models.CharField(default='', max_length=100)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='images/equipment/item_image/default.jpg', max_length=255, null=True, upload_to='images/equipment/item_image')),
                ('receipt', models.FileField(blank=True, default='images/equipment/item_receipt/default.jpg', max_length=255, null=True, upload_to='files/inventory/receipt/equipment/')),
                ('created_at', models.CharField(default='', max_length=50)),
                ('accountable_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'equipment_article',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'equipment_type',
            },
        ),
        migrations.CreateModel(
            name='GovernmentCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'government_company',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'inventory_transfer_method',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'inventory_transfer_status',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True)),
                ('description', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'measurement_unit',
            },
        ),
        migrations.CreateModel(
            name='NameExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
                ('description', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'name_extension',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_to', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('date', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='OfficeSupplyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'office_supply_article',
            },
        ),
        migrations.CreateModel(
            name='OfficeSupplyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_needed', models.CharField(default='', max_length=30)),
                ('requested_by', models.IntegerField(blank=True, default=0)),
                ('request_date', models.CharField(default='', max_length=30)),
                ('is_approved', models.IntegerField(default=0)),
                ('approved_by', models.IntegerField(blank=True, default=0)),
                ('approved_date', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'office_supply_request',
            },
        ),
        migrations.CreateModel(
            name='OfficeSupplyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=255)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('last_modified', models.CharField(default='', max_length=30)),
                ('modified_by', models.IntegerField(default=0)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplyarticle')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.measurementunit')),
            ],
            options={
                'db_table': 'office_supply_stock',
            },
        ),
        migrations.CreateModel(
            name='OfficeSupplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
            ],
            options={
                'db_table': 'office_supply_type',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=55, unique=True)),
                ('code_name', models.CharField(default='', max_length=55, unique=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contenttype')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='ResignedFromGovernmentService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resigned', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'resigned_from_government_service',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_grade', models.CharField(default='', max_length=5, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='SeparatedFromService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_separated', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'separated_from_service',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('session_data', fernet_fields.fields.EncryptedTextField()),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probationary_period', models.IntegerField(default=6)),
                ('am_start_time', models.CharField(blank=True, default='', max_length=30)),
                ('am_end_time', models.CharField(blank=True, default='', max_length=30)),
                ('pm_start_time', models.CharField(blank=True, default='', max_length=30)),
                ('pm_end_time', models.CharField(blank=True, default='', max_length=30)),
                ('grace_before_start_time', models.IntegerField(default=30)),
                ('grace_after_start_time', models.IntegerField(default=15)),
                ('grace_before_end_time', models.IntegerField(default=15)),
                ('grace_after_end_time', models.IntegerField(default=30)),
                ('am_in', models.CharField(default='', max_length=55)),
                ('am_late', models.CharField(default='', max_length=55)),
                ('am_absent', models.CharField(default='', max_length=55)),
                ('am_undertime', models.CharField(default='', max_length=55)),
                ('am_out', models.CharField(default='', max_length=55)),
                ('pm_in', models.CharField(default='', max_length=55)),
                ('pm_late', models.CharField(default='', max_length=55)),
                ('pm_absent', models.CharField(default='', max_length=55)),
                ('pm_undertime', models.CharField(default='', max_length=55)),
                ('pm_out', models.CharField(default='', max_length=55)),
                ('min_emp_age', models.IntegerField(default=18)),
                ('max_emp_age', models.IntegerField(default=60)),
                ('admin_email', models.CharField(default='', max_length=100)),
                ('app_email', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'sex',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=16, unique=True)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.TextField(default='')),
                ('sur_name', models.CharField(default='', max_length=55)),
                ('first_name', models.CharField(default='', max_length=55)),
                ('is_active', models.BooleanField(default=False)),
                ('department', models.IntegerField(default=0, null=True)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('department_head_id', models.IntegerField(default=0)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='images/user/default.jpg', max_length=255, null=True, upload_to='images/user/')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'user_action',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusive_from', models.CharField(default='', max_length=11)),
                ('inclusive_to', models.CharField(default='', max_length=11)),
                ('position_title', models.CharField(default='', max_length=15)),
                ('dept_agency_comp', models.CharField(default='', max_length=55)),
                ('monthly_salary', models.CharField(default='', max_length=30)),
                ('salary_pay_grade', models.CharField(default='', max_length=5)),
                ('appointment_status', models.CharField(default='', max_length=15)),
                ('govt_service', models.CharField(default='', max_length=1)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='VoluntaryWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=55)),
                ('org_address', models.TextField(default='', max_length=255)),
                ('inclusive_from', models.CharField(default='', max_length=11)),
                ('inclusive_to', models.CharField(default='', max_length=11)),
                ('num_of_hours', models.IntegerField(default=0)),
                ('position_work', models.CharField(default='', max_length=30)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'voluntary_work',
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('action', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('ip_address', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_activity',
            },
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(blank=True, default='', max_length=15)),
                ('first_name', models.CharField(blank=True, default='', max_length=15)),
                ('middle_name', models.CharField(blank=True, default='', max_length=55)),
                ('occupation', models.CharField(blank=True, default='', max_length=55)),
                ('emp_bus_name', models.CharField(blank=True, default='', max_length=55)),
                ('emp_bus_addr', models.CharField(blank=True, default='', max_length=55)),
                ('emp_tel_no', models.CharField(blank=True, default='', max_length=55)),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('name_extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nameextension')),
            ],
            options={
                'db_table': 'spouse',
            },
        ),
        migrations.CreateModel(
            name='SolorParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solo_parent', models.BooleanField(default=False)),
                ('id_number', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'solo_parent',
            },
        ),
        migrations.CreateModel(
            name='SkillAndHobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=55, unique=True)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'skill_and_hobby',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=11)),
                ('date_signed', models.CharField(default='', max_length=25)),
                ('attachement', models.ImageField(max_length=255, upload_to='images/signatures/%Y/%m/%d/')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'signature',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipAcadHonorsReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('educational_background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.educationalbackground')),
            ],
            options={
                'db_table': 'scholarship_and_honors_received',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usertype'),
        ),
        migrations.CreateModel(
            name='ResidentialAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_blk_lot_no', models.CharField(blank=True, default='', max_length=55)),
                ('street', models.CharField(blank=True, default='', max_length=30)),
                ('subd_village', models.CharField(blank=True, default='', max_length=55)),
                ('barangay', models.CharField(blank=True, default='', max_length=55)),
                ('city', models.CharField(blank=True, default='', max_length=55)),
                ('province', models.CharField(blank=True, default='', max_length=55)),
                ('country', models.CharField(blank=True, default='', max_length=55)),
                ('is_permanent', models.BooleanField(default=True)),
                ('created_at', models.CharField(blank=True, default='', max_length=30)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'residential_address',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'db_table': 'report_type',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('attachement', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='files/reports/')),
                ('is_archived', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reporttype')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
                ('address', models.TextField(default='', max_length=255)),
                ('tel_no', models.CharField(default='', max_length=11)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55)),
                ('is_vacant', models.BooleanField(blank=True, default=True)),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salary')),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='PersonWithDisability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False)),
                ('id_number', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'person_with_disability',
            },
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_blk_lot_no', models.CharField(blank=True, default='', max_length=55)),
                ('street', models.CharField(blank=True, default='', max_length=30)),
                ('subd_village', models.CharField(blank=True, default='', max_length=55)),
                ('barangay', models.CharField(blank=True, default='', max_length=55)),
                ('city', models.CharField(blank=True, default='', max_length=55)),
                ('province', models.CharField(blank=True, default='', max_length=55)),
                ('country', models.CharField(blank=True, default='', max_length=55)),
                ('created_at', models.CharField(blank=True, default='', max_length=30)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'permanent_address',
            },
        ),
        migrations.CreateModel(
            name='OfficeSupplyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recieved', models.BooleanField(default=False)),
                ('date_recieved', models.CharField(default='', max_length=30)),
                ('recieved_by', models.IntegerField(default=0)),
                ('created_at', models.CharField(default='', max_length=30)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inventorytransfermethod')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplyrequest')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inventorytransferstatus')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplystock')),
            ],
            options={
                'db_table': 'office_supply_transfer',
            },
        ),
        migrations.AddField(
            model_name='officesupplystock',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplytype'),
        ),
        migrations.AddField(
            model_name='officesupplyrequest',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplystock'),
        ),
        migrations.AddField(
            model_name='officesupplyarticle',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplytype'),
        ),
        migrations.CreateModel(
            name='OfficeSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name_code', models.CharField(default='', max_length=55)),
                ('description', models.TextField(default='', max_length=255)),
                ('stock_number', models.CharField(default='', max_length=55, unique=True)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance_per_card', models.IntegerField(blank=True, default=0)),
                ('on_hand_per_count', models.IntegerField(blank=True, default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('shortage', models.IntegerField(blank=True, default=0)),
                ('overage', models.IntegerField(blank=True, default=0)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='images/office_supply/item_image/default.jpg', max_length=255, null=True, upload_to='images/inventory/office_supply/')),
                ('receipt', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='files/inventory/receipt/office_supply/')),
                ('created_at', models.CharField(default='', max_length=30)),
                ('accountable_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplyarticle')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.measurementunit')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officesupplytype')),
            ],
            options={
                'db_table': 'office_supply',
            },
        ),
        migrations.CreateModel(
            name='Oath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='', max_length=30)),
                ('date_accomplished', models.TextField(default='', max_length=15)),
                ('right_thumbmark', models.ImageField(max_length=255, upload_to='folders/righ_thumbmarks/images/')),
                ('person_administiring_oath', models.CharField(default='', max_length=55)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'oath',
            },
        ),
        migrations.CreateModel(
            name='NonAcademicDistinction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=55, unique=True)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'non_academic_distiction',
            },
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(blank=True, default='', max_length=55)),
                ('first_name', models.CharField(blank=True, default='', max_length=55)),
                ('middle_name', models.CharField(default='', max_length=55)),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('name_extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nameextension')),
            ],
            options={
                'db_table': 'mother',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(default='', max_length=30)),
                ('device', models.CharField(default='', max_length=30)),
                ('ip_address', models.CharField(default='', max_length=20)),
                ('login', models.CharField(default='', max_length=30)),
                ('logout', models.CharField(default='--', max_length=30)),
                ('duration', models.CharField(default='--', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'login_history',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blk_lot_no', models.CharField(blank=True, default='', max_length=55)),
                ('street', models.CharField(blank=True, default='', max_length=33)),
                ('subd_village', models.CharField(blank=True, default='', max_length=55)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.barangay')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.province')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, unique=True)),
                ('duration', models.CharField(default='', max_length=30)),
                ('condition', models.CharField(default='', max_length=55)),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sex')),
            ],
            options={
                'db_table': 'leave_type',
            },
        ),
        migrations.CreateModel(
            name='LeaveDetailOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55)),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
            options={
                'db_table': 'leave_detail_option',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.IntegerField(blank=True, default=0)),
                ('available', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
            options={
                'db_table': 'leave_balance',
            },
        ),
        migrations.CreateModel(
            name='LearningDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55, unique=True)),
                ('inclusive_from', models.CharField(default='', max_length=11)),
                ('inclusive_to', models.CharField(default='', max_length=11)),
                ('num_of_hours', models.IntegerField(default=0)),
                ('type_of_ld', models.CharField(default='', max_length=30)),
                ('sponsored_by', models.CharField(default='', max_length=55)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'learning_and_development',
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hired', models.CharField(blank=True, default='', max_length=30)),
                ('start_date', models.CharField(blank=True, default='', max_length=30)),
                ('end_date', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
                ('department_head_id', models.IntegerField(default=0)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
            options={
                'db_table': 'job_history',
            },
        ),
        migrations.CreateModel(
            name='IndigenousGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False)),
                ('id_number', models.TextField(default='', max_length=255)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'indigenous_group',
            },
        ),
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
            ],
            options={
                'db_table': 'group_permissions',
            },
        ),
        migrations.CreateModel(
            name='GovernmentIssuedID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(default='', max_length=30)),
                ('issuance_date', models.CharField(default='', max_length=11)),
                ('issuance_place', models.CharField(default='', max_length=30)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.governmentcompany')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'government_issued_id',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=155)),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(blank=True, default='', max_length=55)),
                ('path', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='files/user/')),
                ('date_uploaded', models.CharField(blank=True, default='', max_length=25)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(blank=True, default='', max_length=55)),
                ('first_name', models.CharField(blank=True, default='', max_length=55)),
                ('middle_name', models.CharField(default='', max_length=55)),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('name_extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nameextension')),
            ],
            options={
                'db_table': 'father',
            },
        ),
        migrations.CreateModel(
            name='EquipmentTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name_code', models.CharField(default='', max_length=55)),
                ('property_number', models.CharField(default='', max_length=55, unique=True)),
                ('description', models.TextField(default='', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('location', models.TextField(default='', max_length=255)),
                ('condition', models.CharField(default='', max_length=100)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='images/equipment/item_image/default.jpg', max_length=255, null=True, upload_to='images/equipment/item_image')),
                ('receipt', models.FileField(blank=True, default='images/equipment/item_receipt/default.jpg', max_length=255, null=True, upload_to='files/inventory/receipt/equipment/')),
                ('created_at', models.CharField(default='', max_length=50)),
                ('accountable_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipmentarticle')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipmenttype')),
            ],
            options={
                'db_table': 'equipment_transfer',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.IntegerField(blank=True, default=0)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.IntegerField(blank=True, default=0)),
                ('approved_date', models.DateTimeField(null=True)),
                ('date_needed', models.CharField(default='', max_length=30)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipment')),
            ],
            options={
                'db_table': 'equipment_request',
            },
        ),
        migrations.AddField(
            model_name='equipmentarticle',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipmenttype'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipmentarticle'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipmenttype'),
        ),
        migrations.CreateModel(
            name='EmployeeStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='New Hire', max_length=100)),
                ('comments', models.TextField(default='Welcome!')),
                ('effective_date', models.CharField(blank=True, default='2022-03-23', max_length=30)),
                ('modified_by', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employeestatus')),
            ],
            options={
                'db_table': 'employee_status_history',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_details', models.CharField(blank=True, default='', max_length=100)),
                ('days_applied', models.IntegerField(default=0)),
                ('start_date', models.CharField(default='', max_length=30)),
                ('end_date', models.CharField(default='', max_length=30)),
                ('supervisor_remarks', models.IntegerField(default=0)),
                ('supervisor_approval_date', models.CharField(default='', max_length=30)),
                ('hr_remarks', models.IntegerField(default=0)),
                ('hr_approval_date', models.CharField(default='', max_length=30)),
                ('is_commutation_requested', models.BooleanField(default=False)),
                ('application_date', models.CharField(default='', max_length=30)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
            options={
                'db_table': 'employee_leave',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employeestatus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employeetype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nameextension'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sex'),
        ),
        migrations.AddField(
            model_name='educationalbackground',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.CreateModel(
            name='DepartmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=155)),
                ('description', models.TextField(blank=True, default='')),
                ('size', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(blank=True, default='', max_length=55)),
                ('path', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='files/department/')),
                ('date_uploaded', models.CharField(blank=True, default='', max_length=25)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'db_table': 'department_file',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.CreateModel(
            name='ConversationReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', max_length=255)),
                ('is_seen', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('visible_to', models.CharField(blank=True, default='', max_length=100)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.conversation')),
            ],
            options={
                'db_table': 'conversation_reply',
            },
        ),
        migrations.CreateModel(
            name='ContributionDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55)),
                ('description', models.CharField(default='', max_length=100)),
                ('government_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.governmentcompany')),
            ],
            options={
                'db_table': 'contribution_deadline',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('max_salary', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employer_share', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.CharField(default='', max_length=30)),
                ('government_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.governmentcompany')),
            ],
            options={
                'db_table': 'contribution',
            },
        ),
        migrations.CreateModel(
            name='CivilServiceEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=55)),
                ('rating', models.CharField(default='', max_length=15)),
                ('exam_date', models.CharField(default='', max_length=15)),
                ('exam_place', models.CharField(default='', max_length=15)),
                ('license_number', models.CharField(default='', max_length=15)),
                ('license_validity_date', models.CharField(default='', max_length=15)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'civil_service_eligibility',
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=55)),
                ('birthdate', models.CharField(default='', max_length=15)),
                ('created_at', models.CharField(default='', max_length=50)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'children',
            },
        ),
        migrations.CreateModel(
            name='Biometrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='', max_length=30)),
                ('issuance_date', models.CharField(default='', max_length=11)),
                ('issuance_place', models.CharField(default='', max_length=30)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'biometrics',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_share', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employer_share_percent', models.CharField(default='', max_length=10)),
                ('employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('employee_share_percent', models.CharField(default='', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_percent', models.CharField(default='', max_length=10)),
                ('contribution_deadline', models.CharField(default='', max_length=30)),
                ('date_added', models.CharField(default='', max_length=30)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('government_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.governmentcompany')),
            ],
            options={
                'db_table': 'benefit',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=12)),
                ('am_in', models.CharField(blank=True, default='', max_length=30)),
                ('am_out', models.CharField(blank=True, default='', max_length=30)),
                ('am_status', models.IntegerField(default=0)),
                ('am_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pm_in', models.CharField(blank=True, default='', max_length=30)),
                ('pm_out', models.CharField(blank=True, default='', max_length=30)),
                ('pm_hrs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pm_status', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='AcquiredResidentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_acquired', models.BooleanField(default=False)),
                ('details', models.TextField(default='', max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'db_table': 'acquired_resident_status',
            },
        ),
    ]
