# Generated by Django 3.1.7 on 2022-04-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.CharField(default='2022-04-01 12:38:10 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeestatushistory',
            name='effective_date',
            field=models.CharField(blank=True, default='2022-04-01 12:38:10 PM', max_length=30),
        ),
    ]
